### ISSUE TITLE
Encoding issue when importing styles to webcomponent

### ISSUE THREAD

**Issue by omaraboualpha** [m4thieulavoie/sass-to-string#487]
```SCSS

@import "../base/colors.scss";
@import "../settings.scss";
@import "../font-definitions";

.k-snackbar {
    display: none;
    max-width: 325px;
    width: 100%;
    border-radius: 3px;
 
    .ri-close-line:before { 
        content: "\eb99"; 
    }  
}
```

In my webcomponent:

```JS
// Create a style tag to be inserted
const style = document.createElement('style');

// Add compiled css to style tag
style.textContent = styles;

this.shadowRoot.prepend(style);
```

Webpack
```JS
      {
        test: /\.component.scss$/,
        exclude: /node_modules/,
        use: [
          "sass-to-string",
          {
            loader: "sass-loader",
            options: {
              sassOptions: {
                outputStyle: "compressed",
              },
            },
          },
        ],
      },
```

The outputted css in the shadow dom outputs a hex-code in the HTML:
```HTML
<style>&#xFEFF;.k-snackbar{display:none;max-width:325px;width:100%;border-radius:3px}.k-snackbar .ri-close-line:before{content:""}</style>
```
The hex code breaks my styling.

As soon as i delete the code with the before the output is as i expect.

Removing this code
```CSS
    .ri-close-line:before { 
        content: "\eb99"; 
    }  
```
Makes the output look like this without the hex code:
```HTML
<style>.k-snackbar{display:none;max-width:325px;width:100%;border-radius:3px}</style>
```

Do you know why this is happening?
